kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: api-allow
spec:
  podSelector:
    matchLabels:
      run: api
  ingress:
  - from:
      - podSelector:
          matchLabels:
            gateway.networking.k8s.io/gateway-name: web-gateway
      - podSelector:
          matchLabels:
            run: web
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-allow
spec:
  podSelector:
    matchLabels:
      run: web
  ingress:
  - from:
    - podSelector:
        matchLabels:
          gateway.networking.k8s.io/gateway-name: web-gateway
